### PR TITLE
Added support for en-US and spaces in path on Windows

### PR DESCRIPTION
**Pull request by anuraagvaidya**
Hey there,

Please feel free to accept the pull request useful for use in English language.

### CODE REVIEW

**Comment by yi-ge** [comment]
Thank you very much.

**Comment by yi-ge** [comment]
I have added you to collaborators.
https://github.com/yi-ge/node-pdf-printer/invitations

**Comment by yi-ge** [comment]
WX20190812-142031@2x

**Comment by yi-ge** [comment]
I am very busy now. Please help to maintain this repositories. Thank you.

**Comment by anuraagvaidya** [comment]
Thank you, no worries. Will do so.

**Pull request merged**
